version: '3.7'

services:

  nginx:
     build:
       context: ./services/nginx
       dockerfile: Dockerfile-prod
     restart: always
     ports:
       - 80:80
     depends_on:
     - pedidos

  pedidos:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile-prod
    volumes:
      - './services/pedidos:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      # - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_prod  # nuevo
      - DATABASE_TEST_URL=postgres://postgres:postgres@pedidos-db:5432/pedidos_test  # nuevo
    depends_on: # nuevo
      - pedidos-db

  pedidos-db: # nuevo
    build:
      context: ./services/pedidos/project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
